### PR TITLE
Weapon switch

### LINKED ISSUE #49: ToolSwitch not switching to sword when attacking
This means after manually switching to sword, if I accidentally hit a block instead of the enemy it switches to that tool instead of the sword, so when I manage to hit the enemy/mob they are hit with like a pickaxe or a shovel

### PR DESCRIPTION
**Pull request by ModProg**
Added weapon Switching
fixes #49

### CODE REVIEW

**Comment by ModProg** [comment]
I thought about adding support for modded swords via the config by adding e.g. for `betterend` and `betternether` these two entries to the list:
`<default> => betternether:cincinnasite_sword, betternether:cincinnasite_sword_diamond, betternether:nether_ruby_sword`
`<default> => betterend:aeternium_sword, betterend:thallasium_sword, betterend:terminite_sword`

Is that something you would approve of?

**Comment by maruohon** [comment]
I would rather not add modded items to the default config, as it's additional maintenance overhead to keep track of. And also it would seem to produce an error in the console for all users who don't have those mods, when it fails to find the item. And I imagine most of the users of this mod don't use any or many "content-adding mods", and even less likely those particular mods.

**Comment by ModProg** [comment]
> I would rather not add modded items to the default config, as it's additional maintenance overhead to keep track of. And also it would seem to produce an error in the console for all users who don't have those mods, when it fails to find the item. And I imagine most of the users of this mod don't use any or many "content-adding mods", and even less likely those particular mods.

makes a lot of sense. I'll keep it like this then. Should these error messages be elevated to in game on screen messages? so users imidiatly know when they make an error?

**Comment by maruohon** [comment]
I merged and slightly cleaned it up locally.

**Pull request closed without merging**
