### PR TITLE
Disable Honey Slowdown and Jump

### PR DESCRIPTION
**Pull request by kerbaras**
Enableing TweakNo `disableHoneyBlockSlowdown` will make the player have normal velocity and jump while standing on honey blocks. Simil to TweakNo `disableSlimeBlockSlowdown`

Disableing it will restore default `velocityMultiplier` and `jumpVelocityMultiplier` values

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
imo there should be two separate toggles - one for jump and one for slowdown, especially for servers that could allow no slowdown, but disallow no jump, and also for people who find one of the features too cheaty. If you decide to take this approach, it would also be nice to add a no bouncy slime, and a better jumping on slime (it is slightly more difficult to jump on slime than a normal block), because it can be annoying, e.g. when working on big flying machine, when you just want to land normally and continue working.

**Comment by kerbaras** [comment]
> also be nice to add a no bouncy slime (...), when you just want to land normally and continue working.

You can shift tho, when u are landing but sure 
(Tho I think it should be in a different PR)

**Comment by kerbaras** [comment]
@maruohon any updates? do you think we should change something?

**Comment by maruohon** [comment]
I think it looks fine, just haven't really put any work on the recent MC versions lately, been focusing on the main dev code.

**Pull request closed without merging**
